import { Link } from 'react-router-dom';
import { cn } from '@elare/utils';

/**
 * The Élaré emblem + wordmark. Links to the app root unless `href` is given
 * (e.g. a cross-site link). `/logo.png` is generated by `pnpm icons` into
 * each site's public folder from logo/elare logo.png.
 */
export function Logo({ className, light, href, size = 'md' }: { className?: string; light?: boolean; href?: string; size?: 'sm' | 'md' | 'lg' }) {
  const mark = { sm: 'h-8 w-8', md: 'h-10 w-10', lg: 'h-14 w-14' }[size];
  const word = { sm: 'text-[1.2rem]', md: 'text-[1.45rem]', lg: 'text-[1.9rem]' }[size];
  const inner = (
    <>
      <img src="/logo.png" alt="" width={256} height={256} className={cn('shrink-0 select-none', mark)} draggable={false} />
      <span className="flex flex-col leading-none">
        <span className={cn('font-semibold tracking-[0.1em]', word, light ? 'text-white' : 'text-ink')}>ÉLARÉ</span>
        <span className={cn('mt-1 font-sans text-[0.58rem] font-semibold uppercase tracking-[0.34em]', light ? 'text-white/80' : 'text-rose')}>Beauty</span>
      </span>
    </>
  );
  const cls = cn('inline-flex items-center gap-2.5 font-display', className);
  return href ? <a href={href} className={cls} aria-label="Élaré Beauty — home">{inner}</a> : <Link to="/" className={cls} aria-label="Élaré Beauty — home">{inner}</Link>;
}
